### PR TITLE
Doesn't work the ChatPane component with IME.

### PR DESCRIPTION
**Pull request by runceel**
This PR is fixing #48.

### CODE REVIEW

**Comment by runceel** [comment]
@markjbrown If you have bandwidth, could you review this PR?

**Comment by markjbrown** [comment]
Hey @joelhulen, can you pull this change into your branch and test? I got a bug report the chat UX did not correctly work with Japanese. Hoping this change will fix it.

If this works, let me know and I'll merge it into this branch and apply to Redis branch as well.

Thanks!

**Comment by joelhulen** [comment]
> Hey @joelhulen, can you pull this change into your branch and test? I got a bug report the chat UX did not correctly work with Japanese. Hoping this change will fix it.
> 
> If this works, let me know and I'll merge it into this branch and apply to Redis branch as well.
> 
> Thanks!

Sure thing. I'll make sure everything works normally, but I might have a hard time testing it in Japanese :)

**Comment by markjbrown** [comment]
I'm going to assume Kazuki-san tested this in Japanese and it works so feel free to just test in English!

Thanks!

**Comment by runceel** [comment]
Thank you for checking. When I tried it locally and checked it, I found the following problem. I don’t know if this is a problem that was originally there or if it was introduced by this fix, but when the chat input field is empty and you press the Enter key, the previous message is resent. If this is a problem that I introduced with my fix, I would like to address it, but I think the cause is that the chat input is being managed by both the UserPrompt property and the UserPromptSet property.

If this is a problem that was introduced by this change, I would like to fix it in this PR. If it is a problem that was already there, I would like to address this issue in a separate PR.

I only changed the trigger for sending messages from onkeydown to onsubmit, so I think it is probably a problem that was already there. Could you give me your opinion?

**Comment by markjbrown** [comment]
Hi @runceel thanks for the explanation. A friend of mine in Japan [told me on twitter](https://twitter.com/kazuyukimiyake/status/1664262956316778501) the chat was not working properly in Japanese. I thought your PR was to fix that.

In either case, thank you for submitting this PR to fix this issue. Much appreciated.  Thanks!

**Comment by runceel** [comment]
@markjbrown 
Miyake-san is one of friends of mine too.
I beleave this PR fix an issue Miyake-san mentioned.

And an another issue I found, I have created separated issue #50.
After merged this PR, I will try to fix #50.

**Comment by joelhulen** [comment]
I verified that this works and implemented the code changes in the `cognitive-search-vector` branch. I also fixed #50 in addition to #48 in the following commit: https://github.com/AzureCosmosDB/VectorSearchAiAssistant/commit/c238144450f2d5fbb8d478777b67118a340e061b

**Comment by joelhulen** [comment]
Closing since I applied the fix in June.

**Pull request closed without merging**
